# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [npm]
    
jobs:
  publish:
    environment: test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: npm

      - name: Install pnpm
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - run: pnpm install

      - name: Configure npm for authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Run release script
        run: pnpm run build:package

      - name: Publish to npm
        run: npm publish
